### ISSUE TITLE
Unable to remove sidebar buttons

### ISSUE THREAD

**Issue by h2110100** [Venca321/Zen-Minimal-Sidebar-Theme#1]
Hi I installed your theme through https://www.zen-browser.app/themes/ab9b529c-63d6-48c0-a59a-4a407c5c3129 but I'm still unable to remove sidebar buttons like history or bookmarks. I'm on windows 11 and I've already tried restarting the browser.

**Comment by h2110100** [comment]
Never mind I didn't rtfm sorry

**Comment by MoshiurRahmanAdib** [comment]
How did you do that?
