### ISSUE TITLE
How to remove buttons?

### ISSUE THREAD

**Issue by slrgt** [Venca321/Zen-Minimal-Sidebar-Theme#4]
The description says this theme allows us to remove buttons but doesn't explain how haha. If I right click a button there is a Remove From Toolbar button but it can't be clicked

**Comment by Opposite34** [comment]
![settings](https://github.com/user-attachments/assets/050842bf-a335-4110-829d-7a54814582ad)
See img above. It is in the Theme Store section of the settings. If your themes don't load try hit Ctrl+R to refresh it.

**Comment by MoshiurRahmanAdib** [comment]
> ![settings](https://private-user-images.githubusercontent.com/54463205/363454393-050842bf-a335-4110-829d-7a54814582ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzA0OTAsIm5iZiI6MTcyNTE3MDE5MCwicGF0aCI6Ii81NDQ2MzIwNS8zNjM0NTQzOTMtMDUwODQyYmYtYTMzNS00MTEwLTgyOWQtN2E1NDgxNDU4MmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA1NTYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNDE3ZGEyMTdhZjQ1MGM5MGE2MDk4NGViZGJjN2NkNzdlYzE4NDI1YjcyMzkwNThmMjJkNGYyMjJjMjQ1NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ir1LP6-FeJu-uZNXQbQU8z59Oy6aDfQL0LK-GlTtLBE) See img above. It is in the Theme Store section of the settings. If your themes don't load try hit Ctrl+R to refresh it.

Where is that setting? I only have this option
![Screenshot 2024-09-01 115718](https://github.com/user-attachments/assets/4bbbc76f-901e-4168-83eb-4aacb87922c7)

**Comment by anilraghuramu** [comment]
I think they changed something now you can't find the settings.

**Comment by anilraghuramu** [comment]
Ah you have to hit Ctrl-R when youre on the page @MoshiurRahmanAdib screenshot-ed
