### ISSUE TITLE
Side panel is cut off when Workspace is disabled and you hide all the buttons (unexpand sidebar)

### ISSUE THREAD

**Issue by Opposite34** [Venca321/Zen-Minimal-Sidebar-Theme#5]
Here's an img, the first one is with every button hided, and the second one is with a random button (sidepanel) enabled (see the sidebar on the left)

![everything hided](https://github.com/user-attachments/assets/5f2b7abf-ec72-49af-a605-965c8f3990f3)
![sidepanel not hided](https://github.com/user-attachments/assets/c1041ff1-687d-4ec0-bdba-c12e56a4ce78)

Step to reproduce:
- Disable the Workspace functionality in `Workspaces`
- Have all the buttons hided in this theme's setting

**Comment by Opposite34** [comment]
I suspects the buttons and the workspace button expands the css padding of the sidebar or something along those lines, which is why this problem occurs, but that's just an educated guess.

**Comment by Samueru-sama** [comment]
Ran into the same issue.

**Comment by vaclavparma** [comment]
Yeah, I think the width of the sidebar is determined by the buttons (and the workspace menu), so without those it probably can happen. I'll look into it.

**Comment by vaclavparma** [comment]
It should be fixed as soon as I merge the new version into the store
