### ISSUE TITLE
All Tab Button doesnt exist anymore and Expand Tab Bar has a checkbox in the setting already you should remove these 2

### ISSUE THREAD

**Issue by ProbablyM-S** [Venca321/Zen-Minimal-Sidebar-Theme#6]
Hi, Love this theme, I use it to hide profile and bookmark buttons :)
as the title says those 2 options are redundant so I think it would be good if you can remove them.
Thanks.

**Comment by vaclavparma** [comment]
Hi. I still have the All tabs button, but I may have an old version (so I would leave it for now if someone else has it there too - I'll remove it in the future). The Expand sidebar button can be hidden elsewhere, so that option can be removed. Thanks for the heads up!

**Comment by ProbablyM-S** [comment]
Hi, with the latest version 1.0.1-a I also finally got all tabs button back after like 20 versions lol so it's not gone ig so its only the expand sidebar button
