### ISSUE TITLE
newtab button can not be hidden using the toggle in this theme

### ISSUE THREAD

**Issue by peshala-prabhapoorna** [Venca321/Zen-Minimal-Sidebar-Theme#7]
hi, this is a very useful theme for me. I wanted to recreate the sidebar look in Edge and this theme is the only way I can do it. 

the new update has made a bunch of changes to the buttons in the sidebar. it doesn't look like the theme is working with the changes.
- hide newtab button doesn't work. 
- I think most of the buttons that used to be there have been removed by default
- sidepanel button is still on the sidebar and it can be hidden using the theme

I've attached pictures with the theme turned off and on. 
I thank you for the effort you put in.

![Screenshot from 2024-09-24 15-02-51](https://github.com/user-attachments/assets/aa42ea37-5856-4096-bab3-a79f8be4c13f)
![Screenshot from 2024-09-24 15-03-04](https://github.com/user-attachments/assets/6b6efce0-e94f-40fd-a10a-ef360be3aa63)
![Screenshot from 2024-09-24 15-07-53](https://github.com/user-attachments/assets/8a59ce5e-adc0-4086-a09a-3d54a0d556ec)

**Comment by ProbablyM-S** [comment]
this theme is redundant for the most part now you can remove and move all of them yourself now by right clicking on tab bar and then clicking on customize toolbar.

this is  not to say this mod was never useful I also used it and liked it but now all the functionality is officially in the browser now, this was a great mod thank you dev for this mod :)
